---

- name: start of tasks debug message
  debug:
    msg: "Starting tasks for {{ inventory_hostname }}"

- name: update repository cache and upgrade all packages with full-upgrade option
  apt:
    update_cache: yes
    upgrade: full

- name: install required packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ required_packages }}"

- name: remove useless packages from the cache
  apt:
    autoclean: yes

- name: remove packages that are no longer required and automatically installed
  apt:
    autoremove: yes

- name: reboot hosts
  reboot:
    reboot_timeout: 3600
    post_reboot_delay: 10
    msg: Rebooting "{{ inventory_hostname }}"
    test_command: uptime
  register: reboot_result

- name: end of tasks debug message
  debug:
    msg: "All the tasks completed successfully for {{ inventory_hostname }}"
  when: reboot_result is succeeded
