---

- name: Start of tasks debug message
  debug:
    msg: "Starting os-update role tasks for {{ inventory_hostname }}"

- name: Update all packages on all nodes
  yum:
    name: "*"
    state: latest
    exclude: kube*
  register: update_result
  notify: reboot hosts
  ignore_errors: yes

- name: End of tasks debug message
  debug:
    msg: "All os-update role tasks completed successfully for {{ inventory_hostname }}"
  when: update_result is succeeded
