---

- name: start of tasks debug message
  debug:
    msg: "Starting tasks for {{ inventory_hostname }}"

- name: update all packages on all nodes
  yum:
    name: "*"
    state: latest
    exclude: kube*
  register: update_result
  notify: reboot hosts
  ignore_errors: yes

- name: reboot hosts
  reboot:
    reboot_timeout: 3600
    post_reboot_delay: 10
    msg: Rebooting "{{ inventory_hostname }}"
    test_command: uptime
  register: reboot_result
  when: update_result is succeeded

- name: end of tasks debug message
  debug:
    msg: "All the tasks completed successfully for {{ inventory_hostname }}"
  when: reboot_result is succeeded
