---

- name: Fact dump
  hosts: all
  tasks:
  - name: Print all facts
    debug:
      var: ansible_facts

  - name: print version of the currently running kernel
    debug:
      var: ansible_facts['kernel']

  - name: print debug message with some facts
    debug:
      msg: >
        The default IPv4 address of {{ ansible_facts.fqdn }} 
        is {{ ansible_facts.default_ipv4.address }}

