---

- name: include kubernetes role
  hosts: kubernetes-cluster
  serial: "100%"
  tasks:
  - include_role:
      name: kubernetes
      tasks_from: main.yml
    tags:
    - kubernetes
    - init_kubernetes
