---

- name: determine the operating system
  hosts: kubernetes-cluster
  tasks:
  
  - name: classify hosts depending on their OS family with gathering some facts        
    group_by:
      key: os_{{ ansible_facts['os_family'] }}
    tags: os-update

- name: import kubernetes role for RedHat based hosts
  hosts: os_RedHat
  serial: "1"
  gather_facts: false
  tasks:

  - include_role:
      name: kubernetes
      tasks_from: os_RedHat_post_install.yml


