---

- name: determine the operating system
  hosts: kubernetes-cluster
  tasks:
  
  - name: classify hosts depending on their OS family with gathering some facts        
    group_by:
      key: os_{{ ansible_facts['os_family'] }}
    tags: 
    - os-update
    - update_os

- name: import os-update role for RedHat based hosts
  hosts: os_RedHat
  gather_facts: false
  serial: 1
  tasks:

  - import_role:
      name: os-update
      tasks_from: os_RedHat.yml
    tags: 
    - os-update
    - update_os

- name: import os-update role for Debian based hosts
  hosts: os_Debian
  gather_facts: false
  serial: 1
  tasks:

  - import_role:
      name: os-update
      tasks_from: os_Debian.yml
    tags: 
    - os-update
    - update_os


