Vagrant.require_version ">= 1.6.0"

Vagrant.configure("2") do |config|
  # create master node first
  config.vm.define "kubemaster01" do |machine|
    machine.vm.box = "centos/7"
    # machine.vm.box = "ubuntu/trusty64"
    machine.ssh.insert_key = false
    machine.vm.hostname = "kubemaster01"
    machine.vm.network "private_network", ip: "10.0.15.10"
    machine.vm.network "forwarded_port", guest: 22, host: 2222
    machine.ssh.forward_agent = true
    machine.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--memory", "3072"]
      v.customize ["modifyvm", :id, "--cpus", "2"]
    end
    machine.vm.provision :ansible do |ansible|
      # Disable default limit to connect to all the machines
      ansible.limit = "all"
      ansible.config_file = "provisioning/ansible.cfg"
      ansible.inventory_path = "provisioning/inventory/hosts.ini"
      ansible.playbook = "provisioning/site.yml"
    end
  end
end
