---

hosts_file_path: /etc/hosts
required_packages:
- vim
- wget
- git
- telnet
- net-tools
- chrony
selinux_config_src_path: selinux_config
selinux_config_dst_path: /etc/selinux/config
fstab_path: /etc/fstab
zone_file_src_path: "/usr/share/zoneinfo/{{ timezone }}"
zone_file_dest_path: /etc/localtime
