---

- include_tasks: os_RedHat.yml
  when: ansible_facts['os_family'] == "RedHat"
  tags: 
  - install_docker
  - docker

- include_tasks: os_Debian.yml
  when: ansible_facts['os_family'] == "Debian"
  tags: 
  - install_docker
  - docker

