---

container_runtime: docker # [crio, docker]
container_networking_interface: calico # [calico, weave-kube]
# more about k8s dashboard: https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/
k8s_dashboard_url: https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/recommended/kubernetes-dashboard.yaml
