---

- hosts: kubernetescluster
  become: yes
  gather_facts: false
  tasks:

    - name: start of play debug message
      debug:
        msg: "change_cgroup playbook is starting for {{ inventory_hostname }}"

    - name: copy template to the /usr/lib/systemd/system/docker.service
      template:
        src: /etc/kubernetes-ansible/templates/docker.service.j2
        dest: /usr/lib/systemd/system/docker.service
        owner: root
        group: root
        mode: 0644

    - name: force systemd to reload
      systemd:
        daemon_reload: yes

    - name: restart docker and kubelet daemons
      service:
        name: "{{ item }}"
        state: restarted
      with_items:
        - docker
        - kubelet

- name: register master node
  import_playbook: masters.yml

