- hosts: masters
  become: yes
  gather_facts: true
  tasks:

    - name: start of play debug message
      debug:
        msg: "masters playbook is starting for {{ inventory_hostname }}"
          
    - name: initialize the cluster
      command: kubeadm init --apiserver-advertise-address=172.28.128.3 --pod-network-cidr=10.244.0.0/16 --service-cidr=10.244.0.0/16 >> /root/cluster_initialized.txt

    - name: create .kube directory
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        remote_src: yes
        owner: root

    - name: pause for 10 seconds
      pause:
        prompt: Pausing 10 seconds before initializing pod network...
        seconds: 10

    - name: install flannel pod network
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.10.0/Documentation/kube-flannel.yml >> /root/pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt


- name: register worker nodes
  import_playbook: workers.yml
