---

- name: restart hosts before finalizing installation
  gather_facts: false
  hosts: kubernetescluster
  tasks:
    
    - name: start of play debug message
      debug:
        msg: "restart_hosts playbook is starting for {{ inventory_hostname }}"
 
    - name: Reboot server
      shell: /sbin/shutdown -r +1
      async: 0
      poll: 0
      ignore_errors: true

    - name: wait for hosts to restart
      wait_for_connection:
        delay: 30
        timeout: 300
    
    - name: execute uptime command
      shell: uptime

    - name: end of play debug message
      debug:
        msg: "all the plays completed for {{ inventory_hostname }}"

