---

- hosts: kubernetes-cluster
  become: yes
  vars_files:
    - /etc/kubernetes-ansible/vars/vars.yml
  gather_facts: true
  tasks:

   - name: Add IP address of all hosts to all hosts
     lineinfile:
       dest: /etc/hosts
       line: "{{ hostvars[item]['ansible_eth1']['ipv4']['address'] }} {{ hostvars[item].inventory_hostname }}"
       state: present
     with_items:
       - kubemaster01
       - kubenode01
       - kubenode02

   - name: remove /var/cache/yum
     file:
       path: /var/cache/yum
       state: absent

   - name: Upgrade all packages
     yum:
       name: "*"
       state: latest
       update_cache: yes
     when: ansible_distribution == "CentOS"

   - name: ensure a list of packages installed
     yum:
       name: "{{ packages }}"
     vars:
       packages:
       - vim
       - wget
       - git
       - telnet
       - net-tools
     when: ansible_distribution == "CentOS"
   
   - name: disable selinux temporarily
     register: selinux_temp
     selinux:
       state: disabled

   - name: disable selinux permanently
     template:
       src: /etc/kubernetes-ansible/templates/config.j2
       dest: /etc/selinux/config
       owner: root
       group: root
       mode: 0644

   # enable br_netfilter kernel module to allow kubernetes pods to communicate across the cluster
   - name: enable br_netfilter
     modprobe:
       name: br_netfilter
       state: present

   - name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
     sysctl:
      name: net.bridge.bridge-nf-call-ip6tables
      value: 1
      state: present

   - name: ensure net.bridge.bridge-nf-call-iptables is set to 1
     sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: 1
      state: present

   - name: remove swapfile from /etc/fstab
     mount:
       name: swap
       fstype: swap
       state: absent

   - name: disable swap
     command: swapoff -a
     when: ansible_swaptotal_mb > 0

   - name: disable service firewalld and ensure it is masked
     systemd:
       name: firewalld
       enabled: no
       masked: yes

- name: install docker-ce
  import_playbook: install_docker.yml

- name: install kubernetes
  import_playbook: install_kubernetes.yml

