---

- name: import variables
  include_vars: "os_{{ ansible_facts['os_family'] }}.yml"
  tags:
  - import
  - kubernetes

- name: start of task debug message
  debug:
    msg: "kubernetes role is starting for {{ inventory_hostname }}"
  tags: kubernetes

- name: remove swapfile
  mount:
    name: swap
    fstype: swap
    state: absent
  register: remove_fstab_result
  tags: preparation

- name: disable swap
  command: swapoff -a
  register: disable_swap_result
  when: 
  - ansible_swaptotal_mb > 0
  - remove_fstab_result is succeeded
  tags: preparation

- name: add Kubernetes' yum repository
  yum_repository:
    name: kubernetes
    description: Kubernetes YUM repository
    baseurl: "{{ k8s_base_url }}"
    gpgkey: "{{ k8s_yum_key }} {{ k8s_rpm_key }}"
    gpgcheck: yes
  tags: kubernetes

- name: install k8s packages
  yum:
    name: "{{ item }}-{{ k8s_version }}"
    state: present
  loop: "{{ k8s_packages }}"
  notify: start and enable docker and kubelet
  tags: kubernetes

- name: include task to init masters
  include_tasks: os_RedHat_init_masters.yml
  when: "inventory_hostname in groups['masters']"
  tags: kubernetes

- name: include task to init workers
  include_tasks: os_RedHat_init_workers.yml
  when: "inventory_hostname in groups['workers']"
  tags: kubernetes

- name: include tasks to post installation process
  include_tasks: os_RedHat_post_install.yml
  when: "inventory_hostname in groups['workers']"
  tags: kubernetes

