---

k8s_base_url: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
k8s_yum_key: https://packages.cloud.google.com/yum/doc/yum-key.gpg 
k8s_rpm_key: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
k8s_packages:
- kubelet
- kubectl
- kubeadm
k8s_master_ip: 10.0.15.10
k8s_pod_subnet: 10.244.0.0/16
output_file: /root/cluster_initialized.txt
k8s_src_conf_path: /etc/kubernetes/admin.conf
k8s_dst_conf_path: /root/.kube/config
flannel_url: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
fstab_path: /etc/fstab
helm_version: v2.12.2

