---

- name: import variables
  include_vars: "os_{{ ansible_facts['distribution'] }}.yml"
  tags:
  - import
  - os-update

- name: update all packages on all nodes
  yum:
    name: "*"
    state: latest
  when: 
  - ansible_facts['os_family'] == "RedHat"
  register: update_result
  tags: os-update

- name: reboot hosts to fully-affect updates
  reboot:
    reboot_timeout: 3600
    post_reboot_delay: 10
    msg: Rebooting "{{ inventory_hostname }}" 
    test_command: uptime
  when: 
  - update_result.changed == false
  - ansible_facts['os_family'] == "RedHat"
  register: reboot_result
  tags: os-update

- name: end of play debug message
  debug:
    msg: "all the plays completed for {{ inventory_hostname }}"
  when: reboot_result is succeeded
  tags: os-update

