---

- name: import variables for RedHat based hosts
  include_vars: "os_{{ ansible_facts['os_family'] }}.yml"
  tags:
  - import
  - preparation

- name: update all packages on all nodes
  yum:
    name: "*"
    state: latest
    exclude: kube*
  register: update_result
  ignore_errors: yes
  tags: os-update

- name: reboot hosts to fully-affect updates
  reboot:
    reboot_timeout: 3600
    post_reboot_delay: 10
    msg: Rebooting "{{ inventory_hostname }}" 
    test_command: uptime
  when: 
  - update_result.changed == true
  register: reboot_result
  tags: os-update

- name: end of play debug message
  debug:
    msg: "all the plays completed for {{ inventory_hostname }}"
  when: update_result is succeeded
  tags: os-update

