---

- name: Import variables
  include_vars: "os_{{ ansible_facts['os_family'] }}.yml"
  tags:
  - import
  - docker

- name: install or upgrade required packages with optimal way
  yum:
    name: "{{ required_packages }}"
    state: latest
  register: install_required_result
  tags: docker

- name: add docker-ce repo
  get_url:
    url: "{{ docker_repo_url }}"
    dest: "{{ docker_repo_dst_path }}"
  register: add_docker_result
  tags: docker

- name: install or upgrade docker
  yum:
    name: docker-ce
    state: latest
  register: install_docker_result
  tags: docker

- name: start and enable docker service
  service: 
    name: docker
    state: started
    enabled: yes
  when: install_docker_result is succeeded
  register: start_docker_result
  tags: docker

