---

- name: Start of tasks debug message
  debug:
    msg: "Starting install_docker tasks for {{ inventory_hostname }}"

- name: Include variables
  include_vars: "os_{{ ansible_facts['os_family'] }}.yml"

- name: Install or upgrade required packages with optimal way
  yum:
    name: "{{ required_packages }}"
    state: latest
  register: install_required_result

- name: Add docker-ce repo
  get_url:
    url: "{{ docker_repo_url }}"
    dest: "{{ docker_repo_dst_path }}"
  register: add_docker_result

- name: Install or upgrade docker
  yum:
    name: docker-ce
    state: latest
  register: install_docker_result
  notify: start and enable docker

- name: Start and enable docker service
  service:
    name: docker
    state: started
    enabled: yes
  when: install_docker_result is succeeded
  register: start_docker_result

- name: End of tasks debug message
  debug:
    msg: "All install_docker tasks completed successfully for {{ inventory_hostname }}"
  when: update_result is succeeded
