---

- name: Start of tasks debug message
  debug:
    msg: "Starting post_install_docker tasks for {{ inventory_hostname }}"

- name: Include variables
  include_vars: "os_{{ ansible_facts['os_family'] }}.yml"

- name: Add user vagrant to docker group
  user:
    name: vagrant
    groups: docker
    append: yes
  register: add_user_result

- name: Change cgroup of docker daemon
  template:
    src: docker.service.j2
    dest: "{{ systemd_docker_path }}"
    owner: root
    group: root
    mode: 0644
  register: change_cgroup_result
  notify: reload and restart docker

- name: End of tasks debug message
  debug:
    msg: "All post_install_docker tasks completed successfully for {{ inventory_hostname }}"
  when: update_result is succeeded
