---

- include_tasks: os_RedHat.yml
  when: ansible_facts['os_family'] == "RedHat"
  tags:
  - prepare_cluster
  - preparation

- include_tasks: os_Debian.yml
  when: ansible_facts['os_family'] == "Debian"
  tags:
  - prepare_cluster
  - preparation

