---

- name: install kubernetes
  gather_facts: false
  vars_files:
    - /etc/kubernetes-ansible/vars/vars.yml
  hosts: kubernetescluster
  tasks:
    
    - name: start of play debug message
      debug:
        msg: "install_kubernetes playbook is starting for {{ inventory_hostname }}"
 
    - name: add Kubernetes' yum repository
      yum_repository:
        name: kubernetes
        description: Kubernetes YUM repository
        baseurl: "{{ kubernetes_base_url }}"
        gpgkey: "{{ kubernetes_gpg_key }}"
        gpgcheck: yes
    
    # kubelet-1.12.0 can not work with flannel 0.10.0, so we will install 1.11.3    
    - name: install kubelet
      yum:
        name: kubelet-1.11.3
        state: present

    # kubelet-1.12.0 can not work with flannel 0.10.0, so we will install 1.11.3 
    - name: install kubeadm
      yum:
        name: kubeadm-1.11.3
        state: present

    # kubelet-1.12.0 can not work with flannel 0.10.0, so we will install 1.11.3     
    - name: install kubectl
      yum:
        name: kubectl-1.11.3
        state: present

    - name: edit /usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf on each node
      template:
        src: /etc/kubernetes-ansible/templates/10-kubeadm.conf.j2
        dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
        owner: root
        group: root
        mode: 0644

    - name: daemon-reload and restart kubelet.service
      systemd:
        state: restarted
        daemon_reload: yes
        name: kubelet

    - name: start and enable docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: start and enable kubelet service
      service:
        name: kubelet
        state: started
        enabled: yes

- name: change cgroup-driver of docker
  import_playbook: change_cgroup.yml

