---

- name: install kubernetes
  gather_facts: false
  hosts: kubernetescluster
  tasks:
    
  - name: classify hosts depending on their OS family with gathering some facts        
    group_by:
      key: os_{{ ansible_facts['os_family'] }}
    tags:
    - install_kubernetes
    - kube-dependencies

- name: import kube-dependencies role for RedHat based hosts
  hosts: os_RedHat
  gather_facts: false
  tasks:

  - import_role:
      name: kube-dependencies
      tasks_from: os_RedHat.yml
    tags: 
    - install_kubernetes
    - kube-dependencies

- name: import kube-dependencies role for Debian based hosts
  hosts: os_Debian
  gather_facts: false
  tasks:

  - import_role:
      name: kube-dependencies
      tasks_from: os_Debian.yml
    tags:
    - install_kubernetes
    - kube-dependencies

- name: import docker role for all hosts
  hosts: kubernetes-cluster
  gather_facts: false
  tasks:

  - import_role:
      name: docker
      tasks_from: main.yml
    tags:
    - install_kubernetes
    - docker

