---

- name: install kubernetes
  gather_facts: false
  hosts: kubernetescluster
  tasks:
    
  - name: classify hosts depending on their OS distribution with gathering some facts        
    group_by:
      key: os_{{ ansible_facts['distribution'] }}
    tags: os-update

- name: install kubernetes for CentOS hosts
  hosts: os_CentOS
  gather_facts: false
  tasks:

  - name: import kube-dependencies role for CentOS hosts
    import_role:
      name: kube-dependencies
      tasks_from: os_CentOS.yml
    tags: 
    - install_kubernetes
    - kube-dependencies

- name: import kube-dependencies role for Ubuntu hosts
  hosts: os_Ubuntu
  gather_facts: false
  tasks:

  - import_role:
      name: kube-dependencies
      tasks_from: os_Ubuntu.yml
    tags:
    - install_kubernetes
    - kube-dependencies

- name: import docker role for all hosts
  hosts: kubernetes-cluster
  gather_facts: false
  tasks:

  - import_role:
      name: docker
      tasks_from: main.yml
    tags:
    - install_kubernetes
    - docker

