- hosts: kubernetescluster
  become: yes
  vars_files:
    - /etc/ansible/vars/vars.yml
  gather_facts: true
  tasks:

   - name: Add IP address of all hosts to all hosts
     lineinfile:
       dest: /etc/hosts
       line: "{{ hostvars[item]['ansible_eth1']['ipv4']['address'] }} {{ hostvars[item].inventory_hostname }}"
       state: present
     with_items:
       - kubemaster01
       - kubenode01
       - kubenode02
   
   - name: ensure a list of packages installed
     yum:
       name: "{{ packages }}"
     vars:
       packages:
       - vim
       - wget
       - git
       - telnet
       - net-tools
   
   - name: disable selinux temporarily
     register: selinux_temp
     selinux:
       state: disabled

   - name: disable selinux permanently
     template:
       src: /etc/ansible/templates/config.j2
       dest: /etc/selinux/config
       owner: root
       group: root
       mode: 0644

   # enable br_netfilter kernel module to allow kubernetes pods to communicate across the cluster
   - name: enable br_netfilter
     modprobe:
       name: br_netfilter
       state: present

   - name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
     sysctl:
      name: net.bridge.bridge-nf-call-ip6tables
      value: 1
      state: present

   - name: ensure net.bridge.bridge-nf-call-iptables is set to 1
     sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: 1
      state: present

   - name: remove swapfile from /etc/fstab
     mount:
       name: swap
       fstype: swap
       state: absent

   - name: disable swap
     command: swapoff -a
     when: ansible_swaptotal_mb > 0


- name: install docker-ce
  import_playbook: install_docker.yml

- name: install kubernetes
  import_playbook: install_kubernetes.yml

