---

- name: determine the operating system
  hosts: kubernetes-cluster
  tasks:
  
  - name: classify hosts depending on their OS family with gathering some facts        
    group_by:
      key: os_{{ ansible_facts['os_family'] }}
    tags: os-update

- name: import preparation role for RedHat based hosts
  hosts: os_RedHat
  gather_facts: false
  tasks:

  - import_role:
      name: preparation
      tasks_from: os_RedHat.yml
    tags: 
    - prepare_cluster
    - preparation

- name: import preparation role for Debian based hosts
  hosts: os_Debian
  gather_facts: false
  tasks:

  - import_role:
      name: preparation
      tasks_from: os_Debian.yml
    tags: 
    - prepare_cluster
    - preparation


