- hosts: masters
  become: yes
  gather_facts: false
  tasks:

    - name: start of play debug message
      debug:
        msg: "workers playbook is starting for {{ inventory_hostname }}"

    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"


- hosts: workers
  become: yes
  tasks:

    - name: start of play debug message
      debug:
        msg: "workers playbook is starting for {{ inventory_hostname }}"
           
    - name: join cluster
      shell: "{{ hostvars[item].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt
      with_items:
        - kubemaster01


- name: do operational tasks
  import_playbook: ops.yml
